version: '3.8'

services:
    eghatha:
        image: eghatha:latest
        build: ./
        ports:
            - 8501:8501
        environment:
            - SUPABASE_URL=${SUPABASE_URL}
            - SUPABASE_KEY=${SUPABASE_KEY}
        volumes:
            - ./app:/app